version: "3.5"

services:
  traefik:
    image: traefik:2.2
    container_name: traefik
    command:
      # - --log.level=DEBUG
      - --api.dashboard
      - --api.insecure
      - --providers.docker
      - --providers.docker.exposedbydefault=true
      - --entrypoints.http.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nizhib
    ports:
      - 80:80
      - 8080:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.localhost`)
      - traefik.http.routers.api.entrypoints=http
      - traefik.http.routers.api.service=api@internal

  albu-front:
    build:
      context: front
      dockerfile: Dockerfile
    networks:
      nizhib:
        aliases:
          - albumentations.localhost
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.albumentations-front.entrypoints=http
      - traefik.http.routers.albumentations-front.rule=Host(`albumentations.localhost`)

  albu-back:
    build:
      context: back
      dockerfile: Dockerfile
    networks:
      - nizhib
    expose:
      - 5000
    labels:
      - traefik.enable=true
      - traefik.http.routers.albumentations-back.entrypoints=http
      - traefik.http.routers.albumentations-back.rule=Host(`albumentations.localhost`) && PathPrefix(`/api`)
      - traefik.http.routers.albumentations-back.middlewares=remove-api
      - traefik.http.middlewares.remove-api.stripprefix.prefixes=/api

networks:
  nizhib:
    name: nizhib
    driver: bridge
