version: "3.5"

services:
  albu-front:
    build:
      context: front
      dockerfile: Dockerfile
    networks:
      - nizhib
    expose:
      - 80
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.albumentations-front.entrypoints=https
      - traefik.http.routers.albumentations-front.rule=Host(`albumentations.ml`)
      - traefik.http.routers.albumentations-front.tls.certresolver=nizhib

  albu-back:
    build:
      context: back
      dockerfile: Dockerfile
    networks:
      - nizhib
    expose:
      - 5000
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.albumentations-back.entrypoints=https
      - traefik.http.routers.albumentations-back.rule=Host(`albumentations.ml`) && PathPrefix(`/api`)
      - traefik.http.routers.albumentations-back.tls.certresolver=nizhib
      - traefik.http.routers.albumentations-back.middlewares=remove-api
      - traefik.http.middlewares.remove-api.stripprefix.prefixes=/api

networks:
  nizhib:
    name: nizhib
    driver: bridge
